---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-image-renderer-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgDBVrzJHuilVHvBzqH346R85K8XBnwAz4bl0NjHHMAqKI8c92DO+0rvDpSOPBlcenH7T0Kb1BevylJVcdl3G8eK6qPYYQWxFvSnl5Nke0SRRCeyVH08J6ONt0+i4mK/2jWzNasFM3SxTJoGJvJOgiw6BofXKwRsPSwMmVXsNnTz0AtWFiad499sG6PJ8ycQ/azSsVMVwZXK7LnYolJwkkbbpxc7GTRRHOjbVs0ZYKuuYgUWvWlgIMxu8gUkdMdp4YmRAoEA474Ib+VaBZI0GG37SdNtOcnXHR3ZLgChghvbqbbMWVN7mv0xgjW/XLkihcZro9R7f63hQC/Nd3E8to8IPshNINwLqDOxabm7AeKNhxw+cUnq0tXm7Wyf+ilLeL0b/xXHVB8DjQPFvBcq0oxUYvvXOJeTv3FNf/OwAOZk+qNVKJ4sMkm4egb1JfS1esI2/w7iV8xC8NZtCMXIXHqNh8X/vxpDR+vU1OYs3e7ODEPkOwUuqf4leqNpeoq/DmyJoSE4wZpJ8U+XtDefepPl/yYvqUzvnjrtRP+zVR0yDZuFx1Pv5mFkYnJiD7FESn6MgRoFXcJ44T2mZKeEtRu62TrAArxM3I4pqIMGEY9IvjIl5iG7e0kxMb70l+l9avnoL/HZz+GaNmdPRhcos/8+BNC4SKxuRBsKkKzdHqm5IubqnBMt3qgJJAtoV9MjEoONCTOc7FlO+JsUrxkm/mOiRrnF9gypuGqyw6FA+48gy2mMItu8EDSM
  template:
    metadata:
      creationTimestamp: null
      name: grafana-image-renderer-token
      namespace: monitoring
