---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAPmgDbRAYck5+1w3Sx2IB95iaKLB0JivvaPBcIffL40h5Aq0xt/I850AVtvTB+mSi/kRrZjCApgOqRclkl+ipBjZOFzjYx5DR1PtrOVGUuDLl/6HE6o1wPwNdpWV3X/gHE30yHTGficPbkkqkbug4oXkHzFxhZllIMijOP3wMDa9gaQeAeb17OjCVpTt4sGfBqOlMfU5LPUdpNj5HjWYMWZHcU3CbLG6vO+FnMrHuU+r83zMHNK5/pEVIbiTlSnE8svjDqhP0Pz/2r6YziFhhs7ZDqsN7REpwaa6CIb/pllMHz6HNsvXJx8OFV06cp40saa4RAlAUVoSNloYMnVE8VKkeQmdbRJFPKPxavKmHwWI1VP3AQ5a2xm1iksAY/uMyiWWuXHx9bU0cTEDd18gcyYAjeWdQB30rOLXtPe/XpDtEdPnAWvi+0oqtZBOVVbsXlG9dcKuS/y5Dwh9kQZGa3b5kWORFxgScumqiuUo9D03fNox5d/xTG/lfJVOczMHRsH8IWJUy5CofPbv2QajG3fZnZs6l9LWUxIfqYOxKPJhoGeVWglGQbqN2emRgttD0MArXtZs0tMJlBOFMogERY4gSZvxrEFrW6gJNDiZZU4YobPaoe5i+a8jZzVZBK5kGz+YOq8r8S9WW2W4f46cyVxXIq1GaJwKu0yCmcYJ6Q57vpmuo8Ds7n5bqmvwfyvVgX4LpC42PpgvdKI5xCtu0EpVb1DiXbhygxeqsBngX5mtCQVxkNw1iz9oh59Ob1jaI=
    admin-user: AgDEf28nFWMrVB5vmZZ/Yxw7bVpXeEhi3Vh2BLHVs6W4brgLz5vsN4kkxkpVUkndoAF0ffbV2iwZnGeAhjQ42YWErfZEj8jd9XdgVS9uLp5T1MfUbDW8qjHlmHr7KFq7bqWeAJ1Z+iXjnA0OdeJjMteK9SG0/XQRUD1n9xZ9td5ws9ET8mfuHIY0BR58XAB0ajy0wGW/LxP+r3kGm+6a3qO0jjnOtD+m6dAIrpnyDgxz4NgbYnr4q0jqUxILxPVdtuimYm3UYZSngBUj09qKahHOmNgaEi0mcJMaPMrXPfL91Nhm0JfiugpiZUE93yPAR7VRV7HG4HYh9AoiEiV6bMqjJyirl/aJwA8sJGKLbJZ5RpmTlSzxpYM5ZB62tXMQBjJ8ippmKhNMpdjzsNdqfp+GZZ2Bds5ew/NeO5ZyJebAMaJN8gwsulWq27wf/yob7ziyh0mSKsVxfrMIHiCYnRQJ8DtCjh/fD2L9Is1bxvNWIPmXCSZmv5Gs+jNcT4L/XOVgD/rC4AgKpZWq7YDSBD2PiI9U//ON6OxFoy5nd8iNh1qAGPt/mnPrTiiiqKqkSKrilwFsJ798aDcdNiTCHz9k1NbrCOZfuJNtaoKLdHMMRhg3YOhCUvuDEjRa/pFxgdayo1FPL6/JsONjbpOBEcNeZ2qkVHYfqBzACj0UxT5dimz9xlLb8KwKPbUL2/jJDBUersDM9g==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
