---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-exporter-config
  namespace: monitoring
spec:
  encryptedData:
    password: AgBy+qy+od/7y/rF8i5RcrB6xRi5EQIQEHD5rA+nuNoXetTaG9mrt9Zcg9eKesxlxIL5fZBQLI4iwUoq2DBSHy/1fUbwuYZCgYBe+BgEEgiQQZcAlw+mudVLH4I3v44onloXGlpDOXkiiRltKl2oSUmgztJiofCdqjHIfAyYtDuuyyN2YX/HE5cJ3tWBUyDcJU8KP7LApf2CEqnEyaVIsx4eR794AZhbh2AodvcD61aOxf6lyyYSRyqeYbA3T3eQllNuyVvfiVwxKlnFkficuN3yqvA5B4PQZpQsXUbtuBkZUNuRbLGcojFXipb1WCLtGvkhMrkvYrp7AkGsoUJutC5ES0A3heJ1ZSbWqQUfnbxFDxtHhtpb0G8xCXICBFKcfMdBwGKc6+k6Otsd7SiGGaMycX/DqrqKdLfcTokxvDkMAWOMmO/cDMFLxnddisrEv9uWBExk3FQXLMjK5++6EcFoZZ5lpSVlZbDJRM5/2d6S6Kw8uRKSAKgHia5uUtqP5vp5b7wK0+xTpRwrj7om4mjEtXS/NZq/np/3+Iei/b4Szs9eNJ7xQs/hBmhoHkBH4ozLbdvGFbwfIwNdABmhVqVcKHsSGTdCnOgx6w+l7gH0Ko1NeGPnoHDFusLstF+KVWqnZ+r5DHebnXSOK4uItv3lKH7UTRGjdCNtqGM5tnMDOkp0qDdnSXx+VySXxQyIDX+XVvA5R2vRT+3TJe9+pPlNWRhlEA==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-exporter-config
      namespace: monitoring
    type: Opaque
