---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pim-tools-token
  namespace: pim
spec:
  encryptedData:
    PIM_TOOLS_TOKEN: AgCv3ZTkc+46FYGcZIVo5aO7pYUv44sjYwumpwsF2fu5xqLaotwJ2BCjkEIgW9TYG3mRHIqf55ZgYIsGn1B5gUPKm/6KnKy+tlcwoALx3kcYUwgkNysFHd1E4Xb9lQLioTR9EKaQK0GZpduawVxJKnwZE5X4lETfWxYbml2J09ypApMhKRu04g8+A/QA0vR4o8LzPRLF7rUtVDfuGgv75tNqhhyS9QJcYMKhHj03whUiY57U+L4YwZ7to0AOOFisd24ZrFSOs7PLsyAkxhbF0Z0TDs6qlKRLpn6t5VAxUmnx5SKZN2TJgosO6GSCtCQuKpk11GXKKHUYCu4wd0hgtMIyCFmw5n2b+ZdSTt20NQW7axIqVHX0trCK0lHNVLTXlFzpccsf770Ws0ERZBBKOYwQW+bpnz0DBAwpQ6NieuhDSirVGcg2qZiz4mff0UR9+XY3UIMgRc2ZQqFgzshom8LwfZUYH6iROo2W+BnsMzXOSwwNy0tgNXjx6xGc0IHBLAWMhG1y6l42Q8ig8HHSr2ocWTTGsDLhK6IJJ+iJhtcVdGWMxjnW7ob5A/9B7MlCkAkiAvMdJS2tc3yRquypvGlA37EYVAB+KEDCdt8T5bAzaq2RzVmZ/GMxLnnt4qq/fwgXAoslrKxplhZoSBAuXR2AFPNTHqxmyZKZMSkQuBpG7msRuISxLBtxkmTbvUh3s9lFkiV9ysvf4fIMW61OJQIpY8+MNdtqT4n6upbrC0SVbgwAsUTly3WnJo5Qr+R8Xwk2RnldXvljQivqhVXCQdGF
  template:
    metadata:
      creationTimestamp: null
      name: pim-tools-token
      namespace: pim
