---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pim-tools-radicale
  namespace: pim
spec:
  encryptedData:
    RADICALE_PASSWORD: AgCxSzFSfoI5OzAb8BTyN2XaeOMJ38/r8tfydCcoBEKY+WqufbCLrnb+7Cg5ZYI1jaBagy5q6lDEcYcGSsJztdUp3rhx7oshBeRTM0whQCjsdN3ojKsEGaREWWxd823ZZKnz2ke21eMsF5rtWHUB6mK08veo+J3X4PmiYMpQvmEb58ocwkv4LvkBv1Z+eSqeNAFijtgsMD/Jc4QYbbrwul4jLiUOPKC9PUf3iUozoMcxJYTydALCVDYEmXjj74Thx8Dk2FcMtazBk7fUt9OGsku3+B12RhodcU7MFhtPVnHQLApryxnS4o0WSHCUo2vy5Un/eF7/WVdnnqkDNp9JZrFeGw9P7ptA5gMRsRvKqYFMdGk6+PPx+/53nRt8PFZDL0wNKomYHn5sEYQO3r0ZzgQD9IHN43cTcUeEanxcsnAdm5xjlhCeSQ+4bMlEC/UW1q5UCUhglKmvgxbtSHLMh0/fAEpKqJmmJI1mn+NQ/WVveZjyzFJiFN40uK3wJdqPpQjcJllplNQ4+HbY87qcc3FqAowqYQkIW0PrX+cMcncC+j1zNXGA4SR7BRVpmcBaZ5GRSrKiS0Z+TsySENmzr/98tOvKEUaS+ewKnzTw+4wGH3jZPHH3J/GwfUjv32VMt/gLpWJLny4oe6FiN0IRoD70VHV6qfGwt2VPNUeQrlCgNiwZG26xGovlHvGaWcqiouBUSYyhc6tIwPBpT8MF2lchL1nV9ZKV2ds=
    RADICALE_USER: AgAcdbYZ0ueRMQ+mW/DNL4D2YfomAEFNRWokVIYVVIOFnta7gb6Wsu9SEJ29oL1gzj8HxzCzOphGS0aQGnpkJ1Syhvp8GvKCVZqtzwLpUO/NYC6caP4sX97oWYuq0Kbf3/C4dt/mvJB1iZV/LjQVZTVO10hpkWuZuLQcRj//O3U8GthxQiuiBKfg7qSbiciox3JjB5tnE0bGo2VEgfHB/wVN3S2oK9Tn+tlRxZbCPjb1C07KKML861KdObtrgbCBv6mxhGF9dsf7RAacWLtYih7TMXB2og0ry2O75wpHY4N38s+/Ln1K2Bq+aM+6DvvFb/ZHXxV+fKrFic5il5fDZHhWEycA4WJcYRadCPll0o7cLD0JL8unz1VQwRJfA7Q9RlNTjb/p1NC5UqE50Qohvew38Czl/EG/tS339NRHxwmg3XSeRZN+XpKw5dlCa7gniAJ137Pt3g6MlGQ/LptJ8JTcklsQGGfKVffoa4FNjZjWTFL4yL83JCh32M//TH2tcyYJM7pJWEWbbxfZoJsBo4f84ATZr3SCmUa/dhlmtJjh4ZxvrYY4NhxuVh9/Z7MncTnTBM5E4SW25m5MezNmgZGxIKU6B+WRBmVV7Qb57uhUf0eTbKnsRcLIbELAAs8SuV3qbl6xDvllPc4RSgxB8BoeytxQBfRvKqaCk79L79wxmXF6HQpHysHM8NaCcpvQc8uWk1IlbXgT
  template:
    metadata:
      creationTimestamp: null
      name: pim-tools-radicale
      namespace: pim
