---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-exporter-config
  namespace: monitoring
spec:
  encryptedData:
    token: AgCJcDBsqdO4I+bN31+JthhsSBcZMJQGVhNxB29AdKy452J5bnS/9r/F1eIZ/nALncEnVAcNmxCSpx3QkTNA0e/g/4p6VHQC34vm8979JkAwRj5ZWveamaChULENB1MS01QdQS7fwgrFhqNwBlI6wYFKzdUHsc5zLtk5lWeVp+Wjw1ceKUy7DxRCX4TWDvlPoRUru/CkWVBpdeBzmB77FCKyz3BHxUtY/+yO6NdPQb+MXGUSFgEgAoDYlxeGBbeWnP+PmSMtAUgoT1lf4BiUjOype5Ta6/OTFl0fgSdr6ZxysOyFvLcRnr8G0hcfGF95GY6ZAkLwuG/BJbwPhazvKDDU7VGs7qng6zP8DRbylizQCXTd5TMdfpxhsBxbAnn5sSypYJoVI3nAjdMsiZeAdXkcqt2cpVe8RFvC8MsmrCrteue8cvYFRPQOKayYwY/qr+CMxVnHvDFUNBs9U3JSOLBQk19Ox65r1Y2Zz9szWXUVfBLVr8EAOQ9W2TGpgq5PthoNxU0sAWFCiFQuUnEsruCryZURm2an7jJDtJHFMqHx/f0i8/GR159mBZz0fv1lVLumm62etWvRYbfv4SpHpXTUoZS2PQP0IsjVgsI1PhBzWLlu0zHm0etrV90KaGTGYaSqsqQpPMO9TnaQuZHDbS4zxfCqSZN16dEu/OThCEd30y1HUOh/fGGjRXIn7oY8J4OZC2KkKfjAiuIGfUsgazGEa3Cz8Q==
  template:
    metadata:
      creationTimestamp: null
      name: plex-exporter-config
      namespace: monitoring
    type: Opaque
