---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radicale-users
  namespace: pim
spec:
  encryptedData:
    users: AgAq0fgyZBGOm6bc5MNBEjn5xbmNuF3vMh1aW778WvWtJMYgzt+w8NT/TvxpSbOo07yeYVeERVz/siYr6hG1g/JkkVxj9c2oDUlFc/PGFZgXioQeZTbn1fRRWQFd29XZVGFPN5bq2sgHSLpM5ShQRvOTDwEspg4LHN0cukVloVMN98WYPNDSYFFCbW8lOGgMNr8VGv1cS91AC+OBdTb9xzod2emDaYCuUjSV+8fKfLeUujKiKA7KEXu6/CL0hi5T2QOIF9A3TAahHRpusyjMlIDhIhnZXX9D22NQjDY8ZKtijI9Q43/8fKF6uwCNYoJjTUIqoe3INozo6TN0hgPHkMk5JUa7/6kma8s3AyU9DfutCvbvSGQJafq5dYkFU4RXaGjeYDi8ORvjZtZAqkp5/eeKAMhUIQpkPzuYu8j16hO/YHizGE872qePE9QBvdU/2xLDa6ej8aVCkUNQ/EK7vW9tCYHlS3qv1shZifKCaG9gk5q9sUQ9onWTF1w1/k8mEngoUonooeI+HqS+VGuvVqobiqunajMQ37pT79Wxm/KwpjE4K+qF7Dm9JtVPAEx8od35Wh88atUqwSll5URkbdn3bd8ZzE/nnvNxqNCJToigP1/7mrxU4d19Df3SRMSvG8IwCk9CyoFYKlT785f3Zz0+FwZ5sakdA3rD9jV0inxxrLhaeIuCmQxbzXQFhJZe+QmeTRPk/MEeJCsa2Dk/yoBOS6sbYFzzVTmOqI24+S0Wi10CY3E+NyK5qVsH/G47V197IeMLHLv4KUQ3AabgUNmKQHqingg=
  template:
    metadata:
      creationTimestamp: null
      name: radicale-users
      namespace: pim
