---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tautulli-config
  namespace: monitoring
spec:
  encryptedData:
    api-key: AgAvidTbsLlSv8kN2oC6cS8VzcXGBA2OT01cdViwxYBM3m4fa8T6+dxeeiRhXOYK8hxjNguwtwdSyD/aJ7PeVfpNNnEQ5aJ8ex8jV7geTlRGZGZVm4redG1WoD83nP95sfUbCAWLnyDuko58hEsOOXoIxywubvzc5FDeFsbPwx7u3OztNlkN3QZmRRCsrbSALxywG7wgbLoPBPwaG/7vxkLggvzrFUylyhq1slryMqfUP7LbvJ8XaJx9f8XJ3J3TaTiFibkS6iG3EVYXPGfXsOs2cIzsn74GIQ7R2x1POCeMQuFiQFiHTV4Rdt5tYxmP13qEKaHEasyK2Dy4Lmf9QnCnhMX1AiaRq5DdmOINgFF/H6mmgjm+y6OH4fXkYwqsQw44lYC/3XljdP8Ft0rVVnuiYCy4YAKayjGAG6Ckci5P3pQ7en2Bc8IB9K3HY4hRs8L2eNkd91yzKz+8Rh+oaV3tm3gPO5iEDHswQu4jFERqfJgyVrdW99AQ6J+N9d5yvEI8aL0tKvbffi9PvhXBb8y6nyB8UBLPC3NyZCDnifgmiVAip0x3tUquIdYe1B7GGZB4sPpETC0CoQfVgwvcI+kyNOsVarNrPioALnxraiplvUJubsfBVk5g/GSJ3YJ/jd7+RwihCVKaEhUKdS1EL2n6VrF+0lTmWEW6oFMRH7tRrll4GBKtCEvHr56SrTwy2XFBeY5NGG/JGmej549TmYdgslNL7/3CJSXaa+qSKPx3jg==
  template:
    metadata:
      creationTimestamp: null
      name: tautulli-config
      namespace: monitoring
