apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-exporter
  namespace: monitoring
  labels:
    app: plex-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex-exporter
  template:
    metadata:
      labels:
        app: plex-exporter
    spec:
      containers:
        - name: plex-exporter
          image: ghcr.io/jsclayton/prometheus-plex-exporter:latest
          ports:
            - containerPort: 9000
          env:
            - name: PLEX_SERVER
              value: "http://192.168.0.202:32400"
            - name: PLEX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: plex-exporter-config
                  key: token
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 96Mi
