apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pim-tools
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/josephbannon-tech/homelab-gitops.git
    targetRevision: HEAD
    path: charts/pim-tools
  destination:
    server: https://kubernetes.default.svc
    namespace: pim
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
